<a href="https://colab.research.google.com/github/sangramshitole07/PythonCourse/blob/main/DataManipulationModule4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Data Manipulation and Analysis with Pandas
Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Pandas.

This is a markdown cell providing context on data manipulation and analysis with Pandas.

In [4]:
import pandas as pd
df=pd.read_csv("/content/sales_data.csv")

This cell imports the pandas library, commonly aliased as `pd`, and then reads a CSV file named `sales_data.csv` from the `/content/` directory into a pandas DataFrame called `df`.

In [5]:
df.head(5)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

This cell displays the first 5 rows of the DataFrame `df`. This is a common practice to quickly inspect the data after loading it.

In [6]:
df.isnull().any()

Product_ID              False
Sale_Date               False
Sales_Rep               False
Region                  False
Sales_Amount            False
Quantity_Sold           False
Product_Category        False
Unit_Cost               False
Unit_Price              False
Customer_Type           False
Discount                False
Payment_Method          False
Sales_Channel           False
Region_and_Sales_Rep    False
dtype: bool

This code checks for the presence of any missing (NaN) values in each column of the DataFrame `df`. `isnull()` returns a boolean DataFrame indicating where values are missing, and `any()` checks if any `True` (missing) values exist in each column.

In [7]:
df.isnull().sum()

Product_ID              0
Sale_Date               0
Sales_Rep               0
Region                  0
Sales_Amount            0
Quantity_Sold           0
Product_Category        0
Unit_Cost               0
Unit_Price              0
Customer_Type           0
Discount                0
Payment_Method          0
Sales_Channel           0
Region_and_Sales_Rep    0
dtype: int64

This cell calculates the total count of missing (NaN) values for each column in the DataFrame `df`. As you can see from the output, there are no missing values in any column.

In [8]:
df_filled=df.fillna(0)

This cell attempts to fill any missing values in the DataFrame `df` with `0`. Since the previous checks confirmed there were no missing values, this operation effectively creates a copy `df_filled` which is identical to `df`.

In [9]:
df

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

This cell simply displays the entire DataFrame `df`.

In [10]:
df['Sales_Amount_update']=df['Sales_Amount'].fillna(df['Sales_Amount'].mean())
df

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep,Sales_Amount_update
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob,5053.97
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob,4384.02
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David,4631.23
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob,2167.94
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie,3750.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie,4733.88
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob,4716.36
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David,7629.70
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David,1629.47
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice,4923.93

This code creates a new column `Sales_Amount_update`. It attempts to fill any missing values in the `Sales_Amount` column with the mean of that column. Again, since there are no missing values in `Sales_Amount`, this operation effectively copies the `Sales_Amount` column to `Sales_Amount_update`.

In [11]:
#rename the columns
df=df.rename(columns={"Sales_Amount" :'Sale'})
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sale,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep,Sales_Amount_update
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob,5053.97
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob,4384.02
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David,4631.23
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob,2167.94
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie,3750.20

This cell renames the column `Sales_Amount` to `Sale` within the DataFrame `df`. It then displays the first 5 rows of the modified DataFrame.

In [12]:
df["Quantity_Sold_"]=df['Quantity_Sold'].fillna(df['Quantity_Sold'].mean().astype(bool))
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sale,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep,Sales_Amount_update,Quantity_Sold_
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob,5053.97,18
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob,4384.02,17
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David,4631.23,30
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob,2167.94,39
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie,3750.20,13

This cell attempts to create a new column `Quantity_Sold_` by filling missing values in `Quantity_Sold` with its mean, then converting that mean to a boolean type.

**Note:** While `fillna` is used, the previous checks confirmed no missing values in `Quantity_Sold`, so this operation has no practical effect on the data here. Also, converting a numerical mean to `astype(bool)` is unusual, as it would result in `True` if the mean is non-zero, and `False` if the mean is zero, which is likely not the intended way to fill numerical data. If there were missing values, `df['Quantity_Sold'].mean()` would be used directly without `astype(bool)` for a numerical fill.

In [13]:
df['New Value']=df['Sale'].apply(lambda x:x*2)
df.head()

,Product_ID,Sale_Date,Sales_Rep,Region,Sale,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep,Sales_Amount_update,Quantity_Sold_,New Value
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob,5053.97,18,10107.94
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob,4384.02,17,8768.04
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David,4631.23,30,9262.46
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob,2167.94,39,4335.88
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie,3750.20,13,7500.40

This code creates a new column named `New Value` by applying a lambda function to each value in the `Sale` column. The lambda function `lambda x: x * 2` simply doubles each sale amount. Finally, it displays the first 5 rows of the DataFrame with the new column.

In [14]:
grouped_mean=df.groupby('Product_ID')['Sale'].mean()
print(grouped_mean)

Product_ID
1001    5063.583750
1002    5526.254615
1003    5038.583333
1004    6431.328182
1005    4373.972727
           ...
1096    5682.530000
1097    5348.284444
1098    4996.997143
1099    5654.103889
1100    3098.054444
Name: Sale, Length: 100, dtype: float64

This cell groups the DataFrame `df` by `Product_ID` and then calculates the mean of the `Sale` column for each `Product_ID`. The result is stored in `grouped_mean`.

In [15]:
#
groudped_agg=df.groupby('Region')['New Value'].agg(['mean','sum','count'])
groudped_agg

                mean         sum  count
Region
East     9580.174373  2519585.86    263
North   10259.269738  2739225.02    267
South   10214.609381  2308501.72    226
West    10127.942049  2471217.86    244

This code groups the DataFrame `df` by `Region` and then calculates multiple aggregate statistics (mean, sum, and count) for the `New Value` column for each region. The results are stored in `groudped_agg` (note the typo in the variable name, it should ideally be `grouped_agg`).

In [16]:
#create a new df and merging two
df1=pd.DataFrame({'key': ['A','B','C'], 'Value1':[1,2,3]})
df2=pd.DataFrame({'key': ['A','B','D'], 'Value2':[4,5,6]})

These lines create two new small DataFrames, `df1` and `df2`, which will be used to demonstrate merging operations. Each DataFrame has a 'key' column and a 'Value' column.

In [17]:
df1

  key  Value1
0   A       1
1   B       2
2   C       3

This cell displays the content of `df1`.

In [18]:
df2

  key  Value2
0   A       4
1   B       5
2   D       6

This cell displays the content of `df2`.

In [19]:
pd.merge(df1,df2,on='key',how='inner')

  key  Value1  Value2
0   A       1       4
1   B       2       5

This cell performs an **inner merge** of `df1` and `df2` based on the common 'key' column. An inner merge keeps only the rows where the 'key' exists in *both* DataFrames ('A' and 'B').

In [20]:
pd.merge(df1,df2,on='key',how='outer')

  key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

This cell performs an **outer merge** of `df1` and `df2` based on the 'key' column. An outer merge keeps all rows from both DataFrames, filling `NaN` for values that don't have a match in the other DataFrame (e.g., 'C' from `df1` and 'D' from `df2`).

###Reading Output from Different Resource

In [21]:
from io import StringIO

This line imports `StringIO` from the `io` module. `StringIO` is used to treat a string as a file-like object, which is useful when pandas functions expect a file path or buffer but you have data as a string.

In [26]:
Data ='{"employee_name" : "James","Email" : "james@gmail.com","job_profile" : [{"title1":"team lead", "title": "Sr.Developer"}]}'
df=pd.read_json(StringIO(Data))
df

,employee_name,Email,job_profile
0,James,james@gmail.com,"{'title1': 'team lead', 'title': 'Sr.Developer'}"

This cell defines a JSON string named `Data` and then uses `pd.read_json()` to parse this string into a DataFrame. `StringIO(Data)` allows `read_json` to treat the string `Data` as if it were a JSON file. Finally, it displays the resulting DataFrame.

In [27]:
df.to_json()

'{"employee_name":{"0":"James"},"Email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"team lead","title":"Sr.Developer"}}}'

This cell converts the DataFrame `df` (created from the JSON string) back into a JSON string using `df.to_json()`. By default, `to_json()` stores the data in a column-oriented format.

In [30]:
df.to_json(orient='records')

'[{"employee_name":"James","Email":"james@gmail.com","job_profile":{"title1":"team lead","title":"Sr.Developer"}}]'

This cell also converts the DataFrame `df` to a JSON string, but uses the `orient='records'` parameter. This format typically represents each row of the DataFrame as a separate JSON object within a list, which is often more intuitive for data exchange.

In [31]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data")

This code reads a CSV file directly from a URL into a DataFrame. This is useful for publicly available datasets.

In [33]:
df.head()

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

This cell displays the first 5 rows of the DataFrame loaded from the wine dataset URL. Notice that the first row of data appears as the header in the output, which suggests the original CSV file did not have a header row. If you want to explicitly define headers, you'd usually pass a `names` parameter to `pd.read_csv`.

In [34]:
df.to_csv("wine.csv")

This cell saves the current DataFrame `df` (the wine dataset) to a CSV file named `wine.csv` in the current working directory.

In [35]:
!pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.1.1)

This cell installs the `lxml` library using `pip`. `lxml` is a high-performance XML and HTML parsing library, often used by pandas for reading HTML tables.

In [36]:
!pip install html5lib
!pip install beautifulsoup4

Requirement already satisfied: html5lib in /usr/local/lib/python3.12/dist-packages (1.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.12/dist-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from html5lib) (0.5.1)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.16.0)

These cells install `html5lib` and `beautifulsoup4` libraries. These are also used for parsing HTML, and pandas often relies on them as backends for its `read_html` function.

In [37]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

This line defines a URL string for the FDIC bank failures list, which contains HTML tables.

In [38]:
df=pd.read_html(url)

This code uses `pd.read_html()` to extract all tables found on the given URL. It returns a list of DataFrames, where each DataFrame corresponds to a table on the webpage.

In [39]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
1,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
2,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
3,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
4,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
5,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
6,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
7,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
8,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
9,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
10,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
11,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
12,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
13,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
14,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
15,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
16,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
17,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
18,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
19,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
20,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
21,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
22,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
23,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
24,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527

This cell displays the first DataFrame from the list of DataFrames returned by `pd.read_html()`, which corresponds to the first table found on the FDIC webpage.

In [40]:
df_excel=pd.read_excel('data.xlsx')

FileNotFoundError: [Errno 2] No such file or directory: 'data.xlsx'

In [43]:
# To fix the FileNotFoundError, you would need to either upload 'data.xlsx' or create a dummy one.
# Let's create a dummy Excel file for demonstration purposes:
import pandas as pd
dummy_data = {'Col1': [1, 2, 3], 'Col2': ['A', 'B', 'C']}
df_excel_dummy = pd.DataFrame(dummy_data)
df_excel_dummy.to_excel('data.xlsx', index=False)

# Now, the original cell's code should work:
df_excel=pd.read_excel('data.xlsx')
display(df_excel.head())

   Col1 Col2
0     1    A
1     2    B
2     3    C

### Error Explanation: `FileNotFoundError`

This cell produced a `FileNotFoundError` because the Excel file named `data.xlsx` does not exist in the current environment's file system. To resolve this, you need to either upload `data.xlsx` to your Colab environment or ensure the correct path to the file is provided if it's located elsewhere.

In [46]:
df_excel.to_pickle('  df_excel')

In [47]:
# Assuming df_excel is now defined from the previous cell (after fixing the FileNotFoundError)
# We'll also remove the leading space from the filename for consistency.
df_excel.to_pickle('df_excel.pkl') # It's good practice to use a .pkl extension

In [45]:
# Assuming 'df_excel.pkl' was successfully saved in the previous step
loaded_df_excel = pd.read_pickle('df_excel.pkl')
display(loaded_df_excel.head())

   Col1 Col2
0     1    A
1     2    B
2     3    C