<a href="https://colab.research.google.com/github/sangramshitole07/PythonCourse/blob/main/Python_course_module3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pandas**
Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [2]:
import pandas as pd

In [3]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to a column in a table.
data=[1,2,3,4,5]
Series=pd.Series(data)
print(Series)
print(type(Series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [4]:
#creating a dictionary from series
data={'a':1,'b':2, 'c':3, 'd':4, 'e':5}
seri_dict=pd.Series(data)
print(seri_dict)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
data =[10,20,30]
index=['a','b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [6]:
#creating data frame from a dict of list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida']
    }
df=pd.DataFrame(data)
print(df)

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [7]:
##creating a data frame from a list of dictionaries
data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}

]
pf=pd.DataFrame(data)
print(pf)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [9]:
import pandas as pd
df_csv = pd.read_csv('/content/sales_data.csv')
display(df_csv.head())

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [19]:
df_csv.head(5)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [20]:
df_csv.tail(5)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [21]:
df_csv['Product_Category']

0        Furniture
1        Furniture
2             Food
3         Clothing
4      Electronics
          ...
995           Food
996       Clothing
997       Clothing
998    Electronics
999           Food
Name: Product_Category, Length: 1000, dtype: object

In [23]:
df_csv.loc[0]

Product_ID                    1052
Sale_Date               2023-02-03
Sales_Rep                      Bob
Region                       North
Sales_Amount               5053.97
Quantity_Sold                   18
Product_Category         Furniture
Unit_Cost                   152.75
Unit_Price                  267.22
Customer_Type            Returning
Discount                      0.09
Payment_Method                Cash
Sales_Channel               Online
Region_and_Sales_Rep     North-Bob
Name: 0, dtype: object

In [24]:
df_csv.iloc[0]

Product_ID                    1052
Sale_Date               2023-02-03
Sales_Rep                      Bob
Region                       North
Sales_Amount               5053.97
Quantity_Sold                   18
Product_Category         Furniture
Unit_Cost                   152.75
Unit_Price                  267.22
Customer_Type            Returning
Discount                      0.09
Payment_Method                Cash
Sales_Channel               Online
Region_and_Sales_Rep     North-Bob
Name: 0, dtype: object

In [25]:
df.at[2,'Age']

np.int64(45)

In [27]:
df_csv.at[0,'Region']

'North'

In [28]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [29]:
df["Salary"]=[5000,60000,7000]
df

    Name  Age       City  Salary
0  Krish   25  Bangalore    5000
1   John   30   New York   60000
2   Jack   45    Florida    7000

In [30]:
df.drop("Salary",axis=1,inplace=True)

In [31]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [32]:
print("Data type :/n", df.dtypes)
print("statistical Summary : /n", df.describe())

Data type :/n Name    object
Age      int64
City    object
dtype: object
statistical Summary : /n              Age
count   3.000000
mean   33.333333
std    10.408330
min    25.000000
25%    27.500000
50%    30.000000
75%    37.500000
max    45.000000

In [33]:
print(df_csv.describe())

        Product_ID  Sales_Amount  Quantity_Sold    Unit_Cost   Unit_Price  \
count  1000.000000   1000.000000    1000.000000  1000.000000  1000.000000
mean   1050.128000   5019.265230      25.355000  2475.304550  2728.440120
std      29.573505   2846.790126      14.159006  1417.872546  1419.399839
min    1001.000000    100.120000       1.000000    60.280000   167.120000
25%    1024.000000   2550.297500      13.000000  1238.380000  1509.085000
50%    1051.000000   5019.300000      25.000000  2467.235000  2696.400000
75%    1075.000000   7507.445000      38.000000  3702.865000  3957.970000
max    1100.000000   9989.040000      49.000000  4995.300000  5442.150000

         Discount
count  1000.00000
mean      0.15239
std       0.08720
min       0.00000
25%       0.08000
50%       0.15000
75%       0.23000
max       0.30000